namespace ChemVerify.Abstractions.Governance;

/// <summary>
/// Canonical, deterministic reasons a finding can be suppressed or downgraded
/// by the governance precision layer. Each value maps to a stable string code
/// emitted on <see cref="Models.ValidationFinding.SuppressionReasonCode"/>
/// so reports and audits can explain *why* a validator finding was muted.
/// </summary>
public enum SuppressionReason
{
    /// <summary>No suppression applied.</summary>
    None = 0,

    /// <summary>Multiple values across distinct steps are expected in multistep synthesis.</summary>
    CrossStepVariationExpected,

    /// <summary>Active vessel/atmosphere is sealed or pressurized — solvent BP exceedances are valid.</summary>
    SealedOrPressurizedSystem,

    /// <summary>Reaction is under explicit reflux conditions consistent with the active solvent.</summary>
    ExplicitRefluxContext,

    /// <summary>Inert atmosphere is intact; apparent containment break is part of a workup transition.</summary>
    WorkupTransitionExpected,

    /// <summary>Aqueous medium appears only after an explicit quench step.</summary>
    PostQuenchAqueousExpected,

    /// <summary>Dryness contradiction occurs after workup, where moisture is expected.</summary>
    PostWorkupDrynessExpected,

    /// <summary>Reagent token is a known placeholder generated by the upstream model template.</summary>
    KnownPlaceholderToken,

    /// <summary>Validator confidence is below the policy-configured minimum for this finding kind.</summary>
    LowConfidenceBelowThreshold,

    /// <summary>Finding is corroborated by no evidence span; treated as informational.</summary>
    NoEvidenceSpan,

    /// <summary>Validator was downgraded by per-validator policy override.</summary>
    PolicyDowngrade
}
