// <auto-generated />
using System;
using ChemVerify.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChemVerify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ChemVerifyDbContext))]
    [Migration("20260215210646_AddClaimEntityKeyAndStepIndex")]
    partial class AddClaimEntityKeyAndStepIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.AiRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectorName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("InputText")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Output")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyProfile")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RiskScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AiRuns", (string)null);
                });

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.ExtractedClaimEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityKey")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedValue")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceLocator")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("StepIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RunId");

                    b.ToTable("ExtractedClaims", (string)null);
                });

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.ValidationFindingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClaimId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<string>("EvidenceRef")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonPayload")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kind")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ValidatorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClaimId");

                    b.HasIndex("RunId");

                    b.ToTable("ValidationFindings", (string)null);
                });

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.ExtractedClaimEntity", b =>
                {
                    b.HasOne("ChemVerify.Infrastructure.Persistence.Entities.AiRunEntity", "Run")
                        .WithMany("Claims")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.ValidationFindingEntity", b =>
                {
                    b.HasOne("ChemVerify.Infrastructure.Persistence.Entities.ExtractedClaimEntity", "Claim")
                        .WithMany()
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ChemVerify.Infrastructure.Persistence.Entities.AiRunEntity", "Run")
                        .WithMany("Findings")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ChemVerify.Infrastructure.Persistence.Entities.AiRunEntity", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Findings");
                });
#pragma warning restore 612, 618
        }
    }
}
